training:
  n_epochs: 100
  lr: 0.001

dataset:
  center_crop_size: 128
  img_resize: &s 32  # Will be resized to a square image
  n_chunks_dataset: 3
  batch_size: 32
  num_workers: 4

model:
  size: *s
  final_size: 4
  n_cb_couplings: 3  # Number of checkerboard couplings at the start of a block
  n_cw_couplings: 3  # Number of channelwise couplings at the end of a block
  n_final_couplings: 3  # Number of coupling layers at the end of the network
  resnet_starting_hidden_channels: 32
  resnet_n_residual_blocks: 1

callbacks:
  reduce_lr_on_plateau:
    factor: 0.5
    patience: 4
    threshold: 0.01
    threshold_mode: abs
  early_stopping:
    patience: 8
    threshold: 0.01
  model_checkpoint:
    save_dir: ../data/realnvp_checkpoints
    filename: realnvp_{epoch:03d}_{score:.3f}.pt
    save_best_only: True
  sample_generation:
    save_dir: ../data/realnvp_generated_samples