name: flows
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - python=3.13
  - pip
  - pip:
    - gdown==5.2.0
    - matplotlib==3.10.1
    - pyyaml==6.0.2
    - scikit-learn==1.6.1
    - torch==2.6.0
    - torchvision==0.21.0