name: llama
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - ipykernel=6.25.0
  - matplotlib=3.8.0
  - pandas=2.1.4
  - python=3.10
  - pip
  - pip:
    - tensorboardX==2.6.2.2
    - tokenizers==0.15.0
    - torch==2.1.2
    - torchvision==0.16.2
    - tqdm==4.66.1
