version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/  # Mount our config file
      - prometheus_data:/prometheus  # Persist data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    # This setting is crucial for letting Prometheus use 'host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana  # Persist data/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: